-- =============================================================
-- Tabel `products` untuk FreshGrove (OPSIONAL).
-- Website memakai pendekatan HYBRID: jika tabel ini ada & terisi,
-- katalog & admin akan memakai data dari sini. Jika tidak, aplikasi
-- otomatis memakai SEED_PRODUCTS di src/lib/products.ts.
--
-- Jalankan di Supabase SQL Editor untuk mengaktifkan mode database.
-- =============================================================

create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  name        text not null,
  category    text not null default 'Tropical',
  price       numeric not null default 0,
  old_price   numeric,
  unit        text not null default 'per kg',
  rating      numeric not null default 4.5,
  reviews     integer not null default 0,
  image       text,
  gallery     jsonb,
  badge       text,
  badge_color text,
  origin      text,
  description text,
  stock       integer default 0,
  tags        jsonb,
  nutrition   jsonb,
  created_at  timestamptz not null default now()
);

-- Aktifkan Row Level Security
alter table public.products enable row level security;

-- Semua orang boleh membaca produk (katalog publik)
drop policy if exists "Products are viewable by everyone" on public.products;
create policy "Products are viewable by everyone"
  on public.products for select
  using (true);

-- Hanya admin yang boleh menamb/ubah/hapus produk.
-- Mengacu ke tabel profiles (role = 'admin') dari schema.sql.
drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
  on public.products for all
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- =============================================================
-- Contoh seed data (samakan dengan SEED_PRODUCTS bila perlu)
-- =============================================================
insert into public.products (name, category, price, old_price, unit, rating, reviews, image, badge, badge_color, origin, description, stock, tags, nutrition)
values
  ('Alphonso Mango', 'Tropical', 32000, 40000, 'per kg', 4.9, 248,
   'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=700&h=700&fit=crop&auto=format',
   'Best Seller', '#F4A623', 'Ratnagiri, India',
   'Mangga Alphonso premium dengan daging tebal, manis legit, dan aroma harum khas.',
   40, '["Manis","Juicy","Premium"]'::jsonb,
   '{"calories":60,"vitaminC":36,"fiber":1.6,"sugar":14}'::jsonb)
on conflict do nothing;
