-- =============================================================
-- FreshGrove — SETUP DATABASE LENGKAP (idempotent / aman diulang)
-- Jalankan SELURUH file ini di Supabase: SQL Editor -> New query ->
-- tempel semua -> Run. Aman dijalankan berkali-kali.
--
-- Mencakup: profiles (+alamat), products (+seed), orders,
-- reviews (ulasan), wishlists (favorit), fungsi is_admin(),
-- trigger pembuatan profil otomatis, RPC place_order (simpan
-- pesanan + kurangi stok), trigger rating otomatis, RLS, dan
-- Storage bucket untuk upload gambar produk & foto profil.
-- =============================================================

-- ---------- 1. PROFILES ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  phone text,
  address text,
  city text,
  postal_code text,
  role text not null default 'customer' check (role in ('admin','customer')),
  created_at timestamptz not null default now()
);
-- tambahkan kolom baru bila tabel sudah ada dari versi lama
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists city text;
alter table public.profiles add column if not exists postal_code text;

-- ---------- 2. PRODUCTS ----------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Tropical',
  price numeric not null default 0,
  old_price numeric,
  unit text not null default 'per kg',
  rating numeric not null default 4.5,
  reviews integer not null default 0,
  image text,
  gallery jsonb,
  badge text,
  badge_color text,
  origin text,
  description text,
  stock integer not null default 0,
  tags jsonb,
  nutrition jsonb,
  created_at timestamptz not null default now()
);

-- ---------- 3. ORDERS ----------
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  shipping_address jsonb,
  items jsonb not null,
  total numeric not null,
  status text not null default 'pending'
    check (status in ('pending','paid','processing','shipped','completed','cancelled')),
  payment_method text default 'qris',
  midtrans_token text,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists payment_method text default 'qris';
alter table public.orders add column if not exists paid_at timestamptz;

-- ---------- 4. REVIEWS (ulasan & rating) ----------
create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (product_id, user_id)
);

-- ---------- 5. WISHLISTS (favorit) ----------
create table if not exists public.wishlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- ---------- 6. FUNGSI is_admin() (hindari rekursi RLS) ----------
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $fn$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$fn$;

-- ---------- 7. TRIGGER buat profil otomatis saat signup ----------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
begin
  insert into public.profiles (id, email, full_name, avatar_url, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url',
    'customer'
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(public.profiles.full_name, excluded.full_name),
        avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url);
  return new;
end;
$fn$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- 8. RPC place_order: simpan pesanan + kurangi stok ----------
create or replace function public.place_order(
  p_order_id text,
  p_items jsonb,
  p_total numeric,
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_shipping jsonb,
  p_payment_method text default 'qris'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_uid uuid := auth.uid();
  v_item jsonb;
  v_pid bigint;
  v_qty integer;
  v_stock integer;
  v_order_id uuid;
begin
  if v_uid is null then
    raise exception 'Harus login untuk membuat pesanan';
  end if;

  -- Kurangi stok untuk tiap item yang punya product_id numerik
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    if (v_item ? 'product_id') and ((v_item->>'product_id') ~ '^[0-9]+$') then
      v_pid := (v_item->>'product_id')::bigint;
      v_qty := coalesce((v_item->>'quantity')::int, 0);
      select stock into v_stock from public.products where id = v_pid for update;
      if v_stock is not null then
        if v_stock < v_qty then
          raise exception 'Stok tidak cukup untuk produk %', v_pid;
        end if;
        update public.products set stock = stock - v_qty where id = v_pid;
      end if;
    end if;
  end loop;

  insert into public.orders (
    order_id, user_id, customer_name, customer_email, customer_phone,
    shipping_address, items, total, status, payment_method
  ) values (
    p_order_id, v_uid, p_customer_name, p_customer_email, p_customer_phone,
    p_shipping, p_items, p_total, 'pending', p_payment_method
  )
  returning id into v_order_id;

  return v_order_id;
end;
$fn$;

grant execute on function public.place_order(text, jsonb, numeric, text, text, text, jsonb, text) to authenticated;

-- ---------- 9. TRIGGER hitung ulang rating produk dari reviews ----------
create or replace function public.recompute_product_rating()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_pid bigint := coalesce(new.product_id, old.product_id);
  v_avg numeric;
  v_cnt integer;
begin
  select round(avg(rating)::numeric, 1), count(*)
    into v_avg, v_cnt
  from public.reviews where product_id = v_pid;
  update public.products
    set rating = coalesce(v_avg, 4.5),
        reviews = coalesce(v_cnt, 0)
  where id = v_pid;
  return null;
end;
$fn$;

drop trigger if exists trg_reviews_rating on public.reviews;
create trigger trg_reviews_rating
  after insert or update or delete on public.reviews
  for each row execute function public.recompute_product_rating();

-- ---------- 10. RLS ----------
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;
alter table public.wishlists enable row level security;

-- profiles
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id or public.is_admin());
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);

-- products (publik baca, admin kelola)
drop policy if exists "products_select_all" on public.products;
create policy "products_select_all" on public.products
  for select using (true);
drop policy if exists "products_admin_manage" on public.products;
create policy "products_admin_manage" on public.products
  for all using (public.is_admin()) with check (public.is_admin());

-- orders (pemilik lihat miliknya, admin lihat & kelola semua)
drop policy if exists "orders_select_own" on public.orders;
create policy "orders_select_own" on public.orders
  for select using (auth.uid() = user_id or public.is_admin());
drop policy if exists "orders_insert_own" on public.orders;
create policy "orders_insert_own" on public.orders
  for insert with check (auth.uid() = user_id);
drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update" on public.orders
  for update using (public.is_admin()) with check (public.is_admin());

-- reviews (publik baca, user kelola miliknya, admin kelola semua)
drop policy if exists "reviews_select_all" on public.reviews;
create policy "reviews_select_all" on public.reviews
  for select using (true);
drop policy if exists "reviews_insert_own" on public.reviews;
create policy "reviews_insert_own" on public.reviews
  for insert with check (auth.uid() = user_id);
drop policy if exists "reviews_update_own" on public.reviews;
create policy "reviews_update_own" on public.reviews
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "reviews_delete_own" on public.reviews;
create policy "reviews_delete_own" on public.reviews
  for delete using (auth.uid() = user_id or public.is_admin());

-- wishlists (user kelola miliknya)
drop policy if exists "wishlists_all_own" on public.wishlists;
create policy "wishlists_all_own" on public.wishlists
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- 11. STORAGE buckets ----------
insert into storage.buckets (id, name, public)
  values ('product-images', 'product-images', true)
  on conflict (id) do nothing;
insert into storage.buckets (id, name, public)
  values ('avatars', 'avatars', true)
  on conflict (id) do nothing;

-- baca publik
drop policy if exists "public_read_images" on storage.objects;
create policy "public_read_images" on storage.objects
  for select using (bucket_id in ('product-images','avatars'));

-- admin kelola gambar produk
drop policy if exists "admin_write_product_images" on storage.objects;
create policy "admin_write_product_images" on storage.objects
  for all to authenticated
  using (bucket_id = 'product-images' and public.is_admin())
  with check (bucket_id = 'product-images' and public.is_admin());

-- user login kelola avatar
drop policy if exists "auth_write_avatars" on storage.objects;
create policy "auth_write_avatars" on storage.objects
  for all to authenticated
  using (bucket_id = 'avatars')
  with check (bucket_id = 'avatars');

-- ---------- 12. SEED PRODUK (hanya jika tabel kosong / id belum ada) ----------
insert into public.products (id, name, category, price, old_price, unit, rating, reviews, image, badge, badge_color, origin, description, stock, tags, nutrition) values
  (1,'Alphonso Mango','Tropical',32000,40000,'per kg',4.9,248,'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=700&h=700&fit=crop&auto=format','Best Seller','#F4A623','Ratnagiri, India','Mangga Alphonso premium dengan daging tebal, manis legit, dan aroma harum khas. Dipanen matang pohon untuk rasa terbaik.',40,'["Manis","Juicy","Premium"]','{"calories":60,"vitaminC":36,"fiber":1.6,"sugar":14}'),
  (2,'Dragon Fruit','Tropical',45000,null,'per pcs',4.7,132,'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=700&h=700&fit=crop&auto=format','Exotic','#E63946','Vietnam','Buah naga merah dengan daging berair, manis menyegarkan, dan kaya antioksidan. Cantik untuk smoothie bowl.',25,'["Antioksidan","Segar"]','{"calories":50,"vitaminC":9,"fiber":3,"sugar":8}'),
  (3,'Strawberry','Berries',28000,35000,'per 250g',4.8,315,'https://images.unsplash.com/photo-1543528176-61b239494933?w=700&h=700&fit=crop&auto=format','Fresh Today','#2D6A4F','Cameron Highlands','Stroberi dataran tinggi yang dipetik pagi hari. Manis-asam seimbang, merah merona, dan wangi.',60,'["Vitamin C","Manis-Asam"]','{"calories":33,"vitaminC":59,"fiber":2,"sugar":5}'),
  (4,'Rambutan','Tropical',18000,null,'per kg',4.6,89,'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=700&h=700&fit=crop&auto=format',null,null,'Kalimantan','Rambutan lokal manis dengan daging kenyal dan mudah lepas dari biji. Favorit musiman keluarga.',80,'["Lokal","Manis"]','{"calories":68,"vitaminC":5,"fiber":0.9,"sugar":13}'),
  (5,'Valencia Orange','Citrus',22000,null,'per kg',4.7,203,'https://images.unsplash.com/photo-1547514701-42782101795e?w=700&h=700&fit=crop&auto=format','Vitamin C+','#F4A623','Malang, Java','Jeruk Valencia berair penuh, manis menyegarkan, ideal untuk jus segar tiap pagi.',100,'["Juicy","Vitamin C"]','{"calories":47,"vitaminC":53,"fiber":2.4,"sugar":9}'),
  (6,'Blueberry','Berries',55000,null,'per 200g',4.9,177,'https://images.unsplash.com/photo-1457296898342-cdd24585d095?w=700&h=700&fit=crop&auto=format','Antioxidant','#5C6BC0','Imported','Blueberry impor pilihan, padat antioksidan, manis lembut. Sempurna untuk sarapan sehat.',35,'["Antioksidan","Superfood"]','{"calories":57,"vitaminC":10,"fiber":2.4,"sugar":10}'),
  (7,'Pomelo','Citrus',25000,null,'per pcs',4.5,64,'https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=700&h=700&fit=crop&auto=format',null,null,'Bali','Jeruk Bali besar dengan daging renyah, manis sedikit pahit yang khas dan menyegarkan.',45,'["Segar","Renyah"]','{"calories":38,"vitaminC":61,"fiber":1,"sugar":8}'),
  (8,'Durian Monthong','Tropical',75000,90000,'per kg',4.8,421,'https://images.unsplash.com/photo-1616096142563-ce95f7932c72?w=700&h=700&fit=crop&auto=format','Premium','#2D6A4F','Thailand','Durian Monthong daging tebal, lembut, manis legit dengan aroma kuat. Raja buah sejati.',18,'["Premium","Creamy"]','{"calories":147,"vitaminC":20,"fiber":3.8,"sugar":27}'),
  (9,'Lychee','Seasonal',38000,null,'per kg',4.7,156,'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=700&h=700&fit=crop&auto=format','In Season','#E63946','China','Leci segar musiman dengan daging bening berair dan manis floral. Stok terbatas.',30,'["Musiman","Floral"]','{"calories":66,"vitaminC":71,"fiber":1.3,"sugar":15}'),
  (10,'Kiwi Gold','Seasonal',42000,null,'per 3 pcs',4.6,98,'https://images.unsplash.com/photo-1585059895524-72359e06133a?w=700&h=700&fit=crop&auto=format',null,null,'New Zealand','Kiwi emas dengan daging kuning manis, lembut, dan rendah asam. Kaya vitamin C.',50,'["Vitamin C","Manis"]','{"calories":60,"vitaminC":92,"fiber":3,"sugar":12}'),
  (11,'Papaya California','Tropical',16000,null,'per kg',4.5,73,'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=700&h=700&fit=crop&auto=format',null,null,'West Java','Pepaya California ukuran pas, daging oranye manis dan lembut. Bagus untuk pencernaan.',70,'["Lokal","Sehat"]','{"calories":43,"vitaminC":62,"fiber":1.7,"sugar":8}'),
  (12,'Raspberry','Berries',62000,null,'per 150g',4.8,112,'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=700&h=700&fit=crop&auto=format','New','#E63946','Imported','Raspberry merah impor, manis-asam menyegarkan dengan tekstur lembut. Cantik untuk dessert.',22,'["Baru","Premium"]','{"calories":52,"vitaminC":26,"fiber":6.5,"sugar":4}')
on conflict (id) do nothing;

-- sinkronkan sequence id agar produk baru tidak bentrok
select setval(pg_get_serial_sequence('public.products','id'), coalesce((select max(id) from public.products), 1));

-- =============================================================
-- SELESAI. Setelah ini, jadikan akun Anda admin:
-- update public.profiles set role='admin'
--   where lower(trim(email)) = lower(trim('EMAIL_ANDA@gmail.com'))
--   returning email, role;
-- =============================================================
